### ISSUE TITLE
TypeError from using type hints in WP hook functions

### ISSUE THREAD

**Issue by mxmkmarquette** [ssnepenthe/wp-hashids#11]
`Fatal error: Uncaught TypeError: WP_Hashids\Hashid_Injector::inject(): Argument #2 ($post) must be of type WP_Post, stdClass given in /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids-0.1.4/src/class-hashid-injector.php:57 Stack trace: #0 [internal function]: WP_Hashids\Hashid_Injector->inject() #1 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids-0.1.4/vendor/ssnepenthe/metis/src/class-proxy.php(39): call_user_func_array() #2 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-hook.php(310): Metis\Proxy->__call() #3 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/plugin.php(205): WP_Hook->apply_filters() #4 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/link-template.php(217): apply_filters() #5 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/providers/class-post-type.php(422): get_permalink() #6 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/providers/class-post-type.php(198): RankMath\Sitemap\Providers\Post_Type->get_url() #7 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/class-generator.php(169): RankMath\Sitemap\Providers\Post_Type->get_sitemap_links() #8 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/class-generator.php(135): RankMath\Sitemap\Generator->build_sitemap() #9 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/class-sitemap-xml.php(159): RankMath\Sitemap\Generator->get_output() #10 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/class-sitemap-xml.php(146): RankMath\Sitemap\Sitemap_XML->build_sitemap() #11 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/class-sitemap-xml.php(85): RankMath\Sitemap\Sitemap_XML->has_sitemap_in_cache() #12 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/class-sitemap-xml.php(75): RankMath\Sitemap\Sitemap_XML->output() #13 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/seo-by-rank-math/includes/modules/sitemap/class-router.php(79): RankMath\Sitemap\Sitemap_XML->__construct() #14 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-hook.php(308): RankMath\Sitemap\Router->request_sitemap() #15 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #16 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/plugin.php(565): WP_Hook->do_action() #17 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-query.php(1127): do_action_ref_array() #18 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-query.php(1820): WP_Query->parse_query() #19 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-query.php(3749): WP_Query->get_posts() #20 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp.php(663): WP_Query->query() #21 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp.php(783): WP->query_posts() #22 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/functions.php(1332): WP->main() #23 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-blog-header.php(16): wp() #24 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/index.php(17): require('...') #25 {main} thrown in /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids-0.1.4/src/class-hashid-injector.php on line 57`

thats the new error i got with rank_math when trying to reach https://dq.saviezvousque.net/post-sitemap.xml, all the other its okay like categories sitemap and else but post not able to reach it error 500

https://dq.saviezvousque.net/post-sitemap.xml

**Comment by ssnepenthe** [comment]
Thanks for the report. I have looked into it and I would consider this a bug with the rank math plugin and I have reported it to them.

However there is also a fix I can make in this plugin. I will try to get to it later today when I have some time.

**Comment by mxmkmarquette** [comment]
yes would be better then wait for them to fix it.

**Comment by ssnepenthe** [comment]
This should be fixed in v0.1.5. Can you try it out and let me know?

If it doesn't work right away you might need to flush transients - it looks like rank math stores the sitemap in a transient that starts with "sitemap_post_rank_math_".

**Comment by mxmkmarquette** [comment]
its working my friend you are simply the best!
