### ISSUE TITLE
when trying in plesk 

### ISSUE THREAD

**Issue by mxmkmarquette** [ssnepenthe/wp-hashids#9]
Problem 1
    - Root composer.json requires hashids/hashids ^2.0.4 -> satisfiable by hashids/hashids[2.0.4].
    - hashids/hashids 2.0.4 requires php ^5.6.4 || ^7.0 -> your php version (8.2.1) does not satisfy that requirement.

im going into /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids/

then

 /opt/plesk/php/8.2/bin/php /usr/lib/plesk-9.0/composer.phar update

and i got the mention error says upper

**Comment by mxmkmarquette** [comment]
and when trying to activate it directly in wp

Fatal error: Uncaught Error: Class "WP_Requirements\Plugin_Checker" not found in /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids-0.1.3/wp-hashids.php:78 Stack trace: #0 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids-0.1.3/wp-hashids.php(115): _wph_init() #1 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-admin/includes/plugin.php(2314): include_once('...') #2 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-admin/plugins.php(192): plugin_sandbox_scrape() #3 {main} thrown in /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids-0.1.3/wp-hashids.php on line 78

**Comment by mxmkmarquette** [comment]
i end up install each depencies but

This page isn’t workingdq.saviezvousque.net is currently unable to handle this request.
HTTP ERROR 500

**Comment by mxmkmarquette** [comment]
i debug

Fatal error: Uncaught Error: Call to undefined method Metis\Container::proxy() in /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids/src/class-admin-provider.php:35 Stack trace: #0 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids/vendor/ssnepenthe/metis/src/class-container.php(77): WP_Hashids\Admin_Provider->boot() #1 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids/vendor/ssnepenthe/metis/src/class-container.php(39): Metis\Container->invoke_on_providers() #2 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-hook.php(308): Metis\Container->boot() #3 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #4 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-includes/plugin.php(517): WP_Hook->do_action() #5 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-settings.php(480): do_action() #6 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-config.php(190): require_once('...') #7 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-load.php(50): require_once('...') #8 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-admin/admin.php(34): require_once('...') #9 /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-admin/index.php(10): require_once('...') #10 {main} thrown in /var/www/vhosts/saviezvousque.net/dq.saviezvousque.net/wp-content/plugins/wp-hashids/src/class-admin-provider.php on line 35

**Comment by ssnepenthe** [comment]
Looks like an issue with PHP8 - try upgrading to v0.1.4 and let me know if that fixes things.

**Comment by mxmkmarquette** [comment]
working now
